src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre_book;

    /**
     * @ORM\Column(type="text")
     */
    private $desc_book;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_book;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $auteur_book;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $img_book;

    /**
     * @ORM\ManyToMany(targetEntity=Categorie::class, mappedBy="livre")
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="livre")
     */
    private $commentaires;

    /**
     * @ORM\ManyToOne(targetEntity=Collect::class, inversedBy="livre")
     */
    private $collection;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreBook(): ?string
    {
        return $this->titre_book;
    }

    public function setTitreBook(string $titre_book): self
    {
        $this->titre_book = $titre_book;

        return $this;
    }

    public function getDescBook(): ?string
    {
        return $this->desc_book;
    }

    public function setDescBook(string $desc_book): self
    {
        $this->desc_book = $desc_book;

        return $this;
    }

    public function getPrixBook(): ?float
    {
        return $this->prix_book;
    }

    public function setPrixBook(float $prix_book): self
    {
        $this->prix_book = $prix_book;

        return $this;
    }

    public function getAuteurBook(): ?string
    {
        return $this->auteur_book;
    }

    public function setAuteurBook(string $auteur_book): self
    {
        $this->auteur_book = $auteur_book;

        return $this;
    }

    public function getImgBook(): ?string
    {
        return $this->img_book;
    }

    public function setImgBook(string $img_book): self
    {
        $this->img_book = $img_book;

        return $this;
    }

    /**
     * @return Collection|Categorie[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Categorie $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addLivre($this);
        }

        return $this;
    }

    public function removeCategory(Categorie $category): self
    {
        if ($this->categories->removeElement($category)) {
            $category->removeLivre($this);
        }

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setLivre($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getLivre() === $this) {
                $commentaire->setLivre(null);
            }
        }

        return $this;
    }

    public function getCollection(): ?Collect
    {
        return $this->collection;
    }

    public function setCollection(?Collect $collection): self
    {
        $this->collection = $collection;

        return $this;
    }

}

src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 */
class Categorie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_cat;

    /**
     * @ORM\ManyToMany(targetEntity=Book::class, inversedBy="categories")
     */
    private $livre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $desc_cat;

    public function __construct()
    {
        $this->livre = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCat(): ?string
    {
        return $this->nom_cat;
    }

    public function setNomCat(string $nom_cat): self
    {
        $this->nom_cat = $nom_cat;

        return $this;
    }

    /**
     * @return Collection|Book[]
     */
    public function getLivre(): Collection
    {
        return $this->livre;
    }

    public function addLivre(Book $livre): self
    {
        if (!$this->livre->contains($livre)) {
            $this->livre[] = $livre;
        }

        return $this;
    }

    public function removeLivre(Book $livre): self
    {
        $this->livre->removeElement($livre);

        return $this;
    }

    public function getDescCat(): ?string
    {
        return $this->desc_cat;
    }

    public function setDescCat(string $desc_cat): self
    {
        $this->desc_cat = $desc_cat;

        return $this;
    }

    public function getDesCat(): ?string
    {
        return $this->des_cat;
    }

    public function setDesCat(?string $des_cat): self
    {
        $this->des_cat = $des_cat;

        return $this;
    }
}

src/Entity/Collect.php
<?php

namespace App\Entity;

use App\Repository\CollectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CollectRepository::class)
 */
class Collect
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_col;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $img_col;

    /**
     * @ORM\OneToMany(targetEntity=Book::class, mappedBy="collection")
     */
    private $livre;

    public function __construct()
    {
        $this->livre = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCol(): ?string
    {
        return $this->nom_col;
    }

    public function setNomCol(string $nom_col): self
    {
        $this->nom_col = $nom_col;

        return $this;
    }

    public function getImgCol(): ?string
    {
        return $this->img_col;
    }

    public function setImgCol(string $img_col): self
    {
        $this->img_col = $img_col;

        return $this;
    }

    /**
     * @return Collection|Book[]
     */
    public function getLivre(): Collection
    {
        return $this->livre;
    }

    public function addLivre(Book $livre): self
    {
        if (!$this->livre->contains($livre)) {
            $this->livre[] = $livre;
            $livre->setCollection($this);
        }

        return $this;
    }

    public function removeLivre(Book $livre): self
    {
        if ($this->livre->removeElement($livre)) {
            // set the owning side to null (unless already changed)
            if ($livre->getCollection() === $this) {
                $livre->setCollection(null);
            }
        }

        return $this;
    }
}

src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contenu_com;

    /**
     * @ORM\Column(type="date")
     */
    private $date_com;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_com;

    /**
     * @ORM\ManyToOne(targetEntity=Book::class, inversedBy="commentaires")
     */
    private $livre;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenuCom(): ?string
    {
        return $this->contenu_com;
    }

    public function setContenuCom(string $contenu_com): self
    {
        $this->contenu_com = $contenu_com;

        return $this;
    }

    public function getDateCom(): ?\DateTimeInterface
    {
        return $this->date_com;
    }

    public function setDateCom(\DateTimeInterface $date_com): self
    {
        $this->date_com = $date_com;

        return $this;
    }

    public function getUserCom(): ?string
    {
        return $this->user_com;
    }

    public function setUserCom(string $user_com): self
    {
        $this->user_com = $user_com;

        return $this;
    }

    public function getLivre(): ?Book
    {
        return $this->livre;
    }

    public function setLivre(?Book $livre): self
    {
        $this->livre = $livre;

        return $this;
    }
}

templates/allLivre.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="grid">
    {% for livre in livres %}
        {% if app.request.get('_route') == 'allLivre' %}
        <article>
            <a href="{{ path('livre_readone', {id:livre.id}) }}"><img class="grid_img" src="img/{{ livre.imgBook }}"></a>
            <a href="{{ path('livre_readone', {id:livre.id}) }}">{{ livre.titreBook }}</a>
        </article>
        {% else %}
            <article>
                <a href="{{ path('livre_readone', {id:livre.id}) }}"><img class="grid_img" src="../img/{{ livre.imgBook }}"></a>
                <a href="{{ path('livre_readone', {id:livre.id}) }}">{{ livre.titreBook }}</a>
            </article>
        {% endif %}
    {% endfor %}
    </div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Bibliothèque{% endblock %}</title>
    <link href="/css/style.css" rel="stylesheet">
    {% block javascripts %}{% endblock %}
</head>
<body>
<nav>
    <div class="left">
        <p>Bibliothèque</p>
    </div>
    <div class="right">
        <a href="{{ path('home') }}">Accueil</a>
        <a href="{{ path('allLivre') }}">Tous les livres</a>
        <a href="{{ path('categorie') }}">Par catégorie</a>
        <a href="{{ path('create') }}">Ajout de contenu</a>
    </div>
</nav>
{% block body %}{% endblock %}
</body>
</html>

templates/categorie.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% if app.request.get('_route') == 'categorie' %}
    <section class="secCat">
        {% for genre in cat %}
            {% if (genre.id%2==0) %}
            <a href="{{ path ('allLivre_cat', {id:genre.id}) }}">
                <div class="cat catright">

                    <div class="divTextR">
                        <p class="nomcat">{{ genre.nomCat }}</p>
                        <p class="desccat">{{ genre.descCat }}</p>
                        <div class="divBtn">
                            <a href="{{ path('categorie_delete', {id:genre.id}) }}" class="btn">Supprimer</a>
                            <a href="{{ path('cat_up', {id:genre.id}) }}" class="btn">Modifier</a>
                        </div>
                    </div>
                </div>
            </a>
            {% else %}
            <a href="{{ path ('allLivre_cat', {id:genre.id}) }}">
                <div class="cat catleft">
                    <div class="divTextL">
                        <p class="nomcat">{{ genre.nomCat }}</p>
                        <p class="desccat">{{ genre.descCat }}</p>
                        <div class="divBtn">
                            <a href="{{ path('categorie_delete', {id:genre.id}) }}" class="btn">Supprimer</a>
                            <a href="{{ path('cat_up', {id:genre.id}) }}" class="btn">Modifier</a>
                        </div>
                    </div>

                </div>
            </a>
            {% endif %}
        {% endfor %}
    </section>
    {% else %}
        <h1>La catégorie a bien été supprimée</h1>
    {% endif %}
{% endblock %}

templates/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
        {% if app.request.get('_route') == 'create' %}
        <div class="div_choix_create">
                <a class="choix" href="{{ path('create_livre') }}">Ajouter un livre</a>
                <a class="choix" href="{{ path('create_cat') }}">Ajouter une catégorie</a>
        </div>
        {% elseif app.request.get('_route') == 'create_livre' %}
        <div class="form">
                <h1>Creation d'un nouveau livre</h1>
                {{ include('form.html.twig') }}
        </div>
        {% elseif app.request.get('_route') == 'create_com' %}
        <div class="form">
                <h1>Creation d'un nouveau commentaire</h1>
                {{ include('form.html.twig') }}
        </div>
        {% else %}
        <div class="form">
                <h1>Creation d'une nouvelle categorie</h1>
                {{ include('form.html.twig') }}
        </div>
        {% endif %}
{% endblock %}

templates/form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('Valider') }}</button>
{{ form_end(form) }}

templates/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1 class="titreHome">{{ titre }}</h1>
    <section class="secCat">
        {% for col in livres %}
            {% if (col.id%2==0) %}
                <a href="{{ path ('allLivre_col', {id:col.id}) }}">
                    <div class="catright imgcol" style="background-image: linear-gradient(to left, rgba(0,0,0,1) 0%, rgba(0,0,0,1) 19%, rgba(255,255,255,0) 100%), url('img/{{ col.imgCol }}')">
                        <p class="titleR">{{ col.nomCol }}</p>
                    </div>
                </a>
            {% else %}
                <a href="{{ path ('allLivre_col', {id:col.id}) }}">
                    <div class="catleft imgcol" style="background-image:linear-gradient(to right, rgba(0,0,0,1) 0%, rgba(0,0,0,1) 19%, rgba(255,255,255,0) 100%), url('img/{{ col.imgCol }}')">
                        <p class="titleL">{{ col.nomCol }}</p>
                    </div>
                </a>
            {% endif %}
        {% endfor %}
    </section>
{% endblock %}

templates/livre.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% if app.request.get('_route') == 'livre_readone' %}
        <section class="livre">
            <h1 class="titleLivre">{{ livre.titreBook }}</h1>
            <div>
                <img src="/img/{{ livre.imgBook }}" class="imgLivre">
                <div class="divInfoLivre">
                    <p>Résumé : {{ livre.descBook }}</p>
                    <p>Auteur : {{ livre.auteurBook }}</p>
                    <p>Prix : {{ livre.prixBook }}€</p>
                    <div>
                        <a href="{{path('livre_delete',{id:livre.id})}}">Supprimer</a>
                        <a href="{{ path('livre_up',{id:livre.id}) }}">Modifier</a>
                    </div>
                </div>

            </div>

            <h3>Espace commentaire</h3>
            <div>
                <a href="{{ path('create_com',{id:livre.id})}}">Ajouter un commentaire</a>
            </div>
            <div class="div_com">
                {% for coms in com %}
                <article class="com">
                    <p>{{ coms.userCom }} {{ coms.dateCom|date("m/d/Y")}}</p>
                    <p>{{ coms.contenuCom }}</p>
                </article>
                {% endfor %}
            </div>
        </section>
    {% else %}
        <h1>Le livre a bien été supprimé</h1>
    {% endif %}
{% endblock %}

templates/update.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% if app.request.get('_route') == 'livre_up' %}

        <h1>Creation d'un nouveau livre</h1>
        {{ include('form.html.twig') }}

    {% else %}

        <h1>Creation d'une nouvelle categorie</h1>
        {{ include('form.html.twig') }}

    {% endif %}
{% endblock %}